# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               "Developer Note"
tagline:             'Day by day, in Everyway, I am getting better and better'
description:         'One a day'
url:                 https://thedevlayer.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              dcp
  url:               https://thedevlayer.github.io
  email:             thedevlayer@gmail.com

# Custom vars
version:             1.0.0

plugins: [jekyll-paginate]

# Tag setting
#collections:
#  tags:
#    output: true
#    permalink: /tags/:path/

#defaults:
#  - scope:
#      path: ''
#      type: tags
#    values:
#      layout: tag

google_analytics:
  ua: 'UA-109898110-1'

github:
  repo: 'https://github.com/thedevlayer/thedevlayer.github.io'

category_dir: category/
tag_dir: tag/

excerpt_separator: ""

  